x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: mysawit-node-exporter
    restart: unless-stopped
    pid: host
    command:
      - "--path.rootfs=/host"
    ports:
      - "9100:9100"
    volumes:
      - "/:/host:ro,rslave"
    logging: *default-logging

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: mysawit-cadvisor
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev/kmsg:/dev/kmsg"
    ports:
      - "8088:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    logging: *default-logging