version: '3.8'

services:

  # ==========================================
  # MICROSERVICES (Auth Service)
  # ==========================================
  auth-service:
    image: ghcr.io/advprog-2026-a18-project/autentikasi-autorisasi-manajemen-pengguna:latest 
    container_name: sawit-auth-service
    environment:
      - SPRING_DATASOURCE_URL=${AUTH_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${AUTH_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${AUTH_DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_FULLNAME=${ADMIN_FULLNAME}
    networks:
      - sawit-network
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # ==========================================
  # MICROSERVICES (Pembayaran Service)
  # ==========================================
  pembayaran-service:
    image: ghcr.io/advprog-2026-a18-project/manajemen-pembayaran:latest 
    container_name: sawit-pembayaran-service
    environment:
      - SPRING_DATASOURCE_URL=${PEMBAYARAN_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${PEMBAYARAN_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${PEMBAYARAN_DB_PASSWORD}
    networks:
      - sawit-network
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # ==========================================
  # MICROSERVICES (Manajemen Kebun Sawit Service)
  # ==========================================
  pembayaran-service:
    image: ghcr.io/advprog-2026-a18-project/mysawit-manajemen-kebun-sawit:latest 
    container_name: sawit-manajemen-kebun-sawit-service
    environment:
      - SPRING_DATASOURCE_URL=${M_KEBUN_SAWIT_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${M_KEBUN_SAWIT_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${M_KEBUN_SAWIT_DB_PASSWORD}
    networks:
      - sawit-network
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  

  # ==========================================
  # API GATEWAY
  # ==========================================
  api-gateway:
    image: ghcr.io/advprog-2026-a18-project/api-sawit-gateway:latest
    container_name: sawit-api-gateway
    ports:
      - "8080:8080" 
    depends_on:
      - auth-service
    environment:
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - sawit-network
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # ==========================================
  # WATCHTOWER 
  # ==========================================
  watchtower:
    image: containrrr/watchtower
    container_name: sawit-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable --cleanup
    restart: always

  # ==========================================
  # DEKLARASI NETWORK 
  # ==========================================
networks:
  sawit-network:
    driver: bridge
